### ISSUE TITLE
editor in readOnly mode can't download attachment

### ISSUE THREAD

**Issue by llcat** [wangfupeng1988/html-wangeditor-demo#1]
i want to download attachement when editor is in readonly mode, how could i implement it?

try it add follow code in demo link
```
 <button id="test-btn">
     开启/关闭
 </button>
document.getElementById('test-btn').addEventListener('click', () => {
                if (window.editor.isDisabled()) {
                    window.editor.enable()
                } else {
                    window.editor.disable()
                }
                const cfg = window.editor.getConfig()
                console.log(cfg)
            })
```
[attachmemt demo](https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html)

**Comment by wangfupeng1988** [comment]
Resolved it, upgrade package https://www.npmjs.com/package/@wangeditor/plugin-upload-attachment 

If you use CDN, it maybe delay.

**Comment by llcat** [comment]
wow! so quickly, thanks~ 😄
